[WIP] SM-60 - Create endpoint to to retrieve a material for reparation request
KA-Huis/space-management pull request #77
Opened 2022-04-18 21:37 UTC by Hoopless

# SM-60 - Create endpoint to to retrieve a material for reparation request

**Changelogs**
- Added gitignore files
- Added packages for filters and sorting and json pagination.
- Created Index for all material reparations
- Edited env for testing; we should pick this up.

**Notes**
Regarding the .env.testing; we should find a way to use both methods to test.  We should either gitignore phpunit.xml  or .env.testing and write some documentation on the information in the file.

We will decide tomorrow if we can. For now, I will keep this way of working.

2022-04-19 17:08 UTC, cyrildewit commented on .env.testing
> +APP_URL=http://space-management.test/
These changes shouldn't be commited, but I saw that you already addressed an issue with this file in your description, so we will talk about it in our meeting todayl

2022-04-19 17:08 UTC, cyrildewit commented on config/app.php
> +        Spatie\JsonApiPaginate\JsonApiPaginateServiceProvider::class,
These aren't necessary, because they're auto discovered by the framework.

2022-04-19 17:08 UTC, cyrildewit commented on database/migrations/2022_04_14_101120_create_sessions_table.php
> +        return $this->application->environment(['acceptance', 'local', 'testing']);
Why don't we use redis? There is already a container available.

2022-04-19 17:08 UTC, cyrildewit commented on phpunit.xml
> -        <report>
Why did you remove this? I think it's necessary for CodeCov.io.

2022-04-19 17:08 UTC, cyrildewit commented on phpunit.xml
> +        <server name="TELESCOPE_ENABLED" value="false"/>
Telescope is not installed, so this can be removed.

2022-04-19 17:08 UTC, cyrildewit commented on phpunit.xml
> +        <server name="DB_DATABASE" value="spacemangement_dev"/>
I thin this will break the docker setup.

2022-04-19 17:17 UTC, cyrildewit requested changes
See comments

2022-04-19 18:31 UTC, Hoopless commented
Add changes regarding Ticket #55

2022-04-20 09:36 UTC, cyrildewit requested changes
See comments

2022-04-20 09:36 UTC, cyrildewit commented on app/Http/Controllers/API/V1/ReparationRequestMaterialController.php
> +        $materialRequest = QueryBuilder::for(ReparationRequestMaterial::class)
`$materialRequest` is a little bit confusing. I thinks `$material` or the full out version `$reparationRequestMaterial` is more specific.

2022-04-20 09:36 UTC, cyrildewit commented on database/migrations/2020_04_14_101120_create_cache_table.php
> +        return $this->application->environment(['acceptance', 'local', 'testing']);
We could eliminate the need for this migration on the local and testing environment if everyone uses the docker setup locally.

2022-04-20 09:36 UTC, cyrildewit commented on app/Http/Controllers/API/V1/ReparationRequestMaterialController.php
> +        return $materialRequest;
We agreed on using specific resource classed right? Then this should be picked up.

2022-04-20 09:36 UTC, cyrildewit commented on app/Http/Controllers/API/V1/ReparationRequestMaterialController.php
> +        return $materialRequest;
We agreed on using specific resource classed right? Then this should be picked up.

2022-04-21 17:23 UTC, Hoopless commented
The following commit has the changes:

# SM-60: Create endpoint to retrieve materials - Pull request feedback
This is a combination of both commented feedback and feedback we have discussed from the other pull request.

Could you please review the pull request @cyrildewit?

2022-04-21 17:34 UTC, cyrildewit commented on routes/api/v1.php
> +            ->prefix('reparation_requests_material')
I think the convention is usually to use the plurar form. I've used it too. For example: https://stripe.com/docs/api/terminal/locations/update

2022-04-21 17:46 UTC, cyrildewit commented on routes/api/v1.php
> +            ->prefix('reparation_requests_material')
```suggestion
            ->prefix('reparation_request_materials')
```

2022-04-21 17:51 UTC, cyrildewit approved these changes
LGTM

2022-04-21 17:51 UTC, merged